export const schedule_sample = {
  mon: {
    "08-09": { class_id: "", subjectcode: "", slotdata: "" },
    "09-10": { class_id: "", subjectcode: "", slotdata: "" },
    "10-11": { class_id: "", subjectcode: "", slotdata: "" },
    "11-12": { class_id: "", subjectcode: "", slotdata: "" },
    "12-01": { class_id: "", subjectcode: "", slotdata: "" },
    "01-02": { class_id: "", subjectcode: "", slotdata: "" },
    "02-03": { class_id: "", subjectcode: "", slotdata: "" },
    "03-04": { class_id: "", subjectcode: "", slotdata: "" },
    "04-05": { class_id: "", subjectcode: "", slotdata: "" },
    "05-06": { class_id: "", subjectcode: "", slotdata: "" },
  },
  tue: {
    "08-09": { class_id: "", subjectcode: "", slotdata: "" },
    "09-10": { class_id: "", subjectcode: "", slotdata: "" },
    "10-11": { class_id: "", subjectcode: "", slotdata: "" },
    "11-12": { class_id: "", subjectcode: "", slotdata: "" },
    "12-01": { class_id: "", subjectcode: "", slotdata: "" },
    "01-02": { class_id: "", subjectcode: "", slotdata: "" },
    "02-03": { class_id: "", subjectcode: "", slotdata: "" },
    "03-04": { class_id: "", subjectcode: "", slotdata: "" },
    "04-05": { class_id: "", subjectcode: "", slotdata: "" },
    "05-06": { class_id: "", subjectcode: "", slotdata: "" },
  },
  wed: {
    "08-09": { class_id: "", subjectcode: "", slotdata: "" },
    "09-10": { class_id: "", subjectcode: "", slotdata: "" },
    "10-11": { class_id: "", subjectcode: "", slotdata: "" },
    "11-12": { class_id: "", subjectcode: "", slotdata: "" },
    "12-01": { class_id: "", subjectcode: "", slotdata: "" },
    "01-02": { class_id: "", subjectcode: "", slotdata: "" },
    "02-03": { class_id: "", subjectcode: "", slotdata: "" },
    "03-04": { class_id: "", subjectcode: "", slotdata: "" },
    "04-05": { class_id: "", subjectcode: "", slotdata: "" },
    "05-06": { class_id: "", subjectcode: "", slotdata: "" },
  },
  thu: {
    "08-09": { class_id: "", subjectcode: "", slotdata: "" },
    "09-10": { class_id: "", subjectcode: "", slotdata: "" },
    "10-11": { class_id: "", subjectcode: "", slotdata: "" },
    "11-12": { class_id: "", subjectcode: "", slotdata: "" },
    "12-01": { class_id: "", subjectcode: "", slotdata: "" },
    "01-02": { class_id: "", subjectcode: "", slotdata: "" },
    "02-03": { class_id: "", subjectcode: "", slotdata: "" },
    "03-04": { class_id: "", subjectcode: "", slotdata: "" },
    "04-05": { class_id: "", subjectcode: "", slotdata: "" },
    "05-06": { class_id: "", subjectcode: "", slotdata: "" },
  },
  fri: {
    "08-09": { class_id: "", subjectcode: "", slotdata: "" },
    "09-10": { class_id: "", subjectcode: "", slotdata: "" },
    "10-11": { class_id: "", subjectcode: "", slotdata: "" },
    "11-12": { class_id: "", subjectcode: "", slotdata: "" },
    "12-01": { class_id: "", subjectcode: "", slotdata: "" },
    "01-02": { class_id: "", subjectcode: "", slotdata: "" },
    "02-03": { class_id: "", subjectcode: "", slotdata: "" },
    "03-04": { class_id: "", subjectcode: "", slotdata: "" },
    "04-05": { class_id: "", subjectcode: "", slotdata: "" },
    "05-06": { class_id: "", subjectcode: "", slotdata: "" },
  },
  sat: {
    "08-09": { class_id: "", subjectcode: "", slotdata: "" },
    "09-10": { class_id: "", subjectcode: "", slotdata: "" },
    "10-11": { class_id: "", subjectcode: "", slotdata: "" },
    "11-12": { class_id: "", subjectcode: "", slotdata: "" },
    "12-01": { class_id: "", subjectcode: "", slotdata: "" },
    "01-02": { class_id: "", subjectcode: "", slotdata: "" },
    "02-03": { class_id: "", subjectcode: "", slotdata: "" },
    "03-04": { class_id: "", subjectcode: "", slotdata: "" },
    "04-05": { class_id: "", subjectcode: "", slotdata: "" },
    "05-06": { class_id: "", subjectcode: "", slotdata: "" },
  },
  sun: {
    "08-09": { class_id: "", subjectcode: "", slotdata: "" },
    "09-10": { class_id: "", subjectcode: "", slotdata: "" },
    "10-11": { class_id: "", subjectcode: "", slotdata: "" },
    "11-12": { class_id: "", subjectcode: "", slotdata: "" },
    "12-01": { class_id: "", subjectcode: "", slotdata: "" },
    "01-02": { class_id: "", subjectcode: "", slotdata: "" },
    "02-03": { class_id: "", subjectcode: "", slotdata: "" },
    "03-04": { class_id: "", subjectcode: "", slotdata: "" },
    "04-05": { class_id: "", subjectcode: "", slotdata: "" },
    "05-06": { class_id: "", subjectcode: "", slotdata: "" },
  },
};

